import time

eventTimes = [
    [time.strptime("00:00", "%H:%M"), Admiral Taidha Covington]
    [time.strptime("00:00", "%H:%M"), Tequatl the Sunless]
    [time.strptime("00:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("00:30", "%H:%M"), Megadestroyer]
    [time.strptime("00:45", "%H:%M"), Fire Elemental]
    [time.strptime("01:00", "%H:%M"), The Shatterer]
    [time.strptime("01:00", "%H:%M"), Evolved Jungle Wurm]
    [time.strptime("01:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("01:30", "%H:%M"), Modniir Ulgoth]
    [time.strptime("01:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("02:00", "%H:%M"), Golem Mark II]
    [time.strptime("02:00", "%H:%M"), Karka Queen]
    [time.strptime("02:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("02:30", "%H:%M"), Claw of Jormag]
    [time.strptime("02:45", "%H:%M"), Fire Elemental]
    [time.strptime("03:00", "%H:%M"), Admiral Taidha Covington]
    [time.strptime("03:00", "%H:%M"), Tequatl the Sunless]
    [time.strptime("03:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("03:30", "%H:%M"), Megadestroyer]
    [time.strptime("03:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("04:00", "%H:%M"), The Shatterer]
    [time.strptime("04:00", "%H:%M"), Evolved Jungle Wurm]
    [time.strptime("04:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("04:30", "%H:%M"), Modniir Ulgoth]
    [time.strptime("04:45", "%H:%M"), Fire Elemental]
    [time.strptime("05:00", "%H:%M"), Golem Mark II]
    [time.strptime("05:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("05:30", "%H:%M"), Claw of Jormag]
    [time.strptime("05:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("06:00", "%H:%M"), Admiral Taidha Covington]
    [time.strptime("06:00", "%H:%M"), Karka Queen]
    [time.strptime("06:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("06:30", "%H:%M"), Megadestroyer]
    [time.strptime("06:45", "%H:%M"), Fire Elemental]
    [time.strptime("07:00", "%H:%M"), The Shatterer]
    [time.strptime("07:00", "%H:%M"), Tequatl the Sunless]
    [time.strptime("07:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("07:30", "%H:%M"), Modniir Ulgoth]
    [time.strptime("07:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("08:00", "%H:%M"), Golem Mark II]
    [time.strptime("08:00", "%H:%M"), Evolved Jungle Wurm]
    [time.strptime("08:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("08:30", "%H:%M"), Claw of Jormag]
    [time.strptime("08:45", "%H:%M"), Fire Elemental]
    [time.strptime("09:00", "%H:%M"), Admiral Taidha Covington]
    [time.strptime("09:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("09:30", "%H:%M"), Megadestroyer]
    [time.strptime("09:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("10:00", "%H:%M"), The Shatterer]
    [time.strptime("10:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("10:30", "%H:%M"), Modniir Ulgoth]
    [time.strptime("10:30", "%H:%M"), Karka Queen]
    [time.strptime("10:45", "%H:%M"), Fire Elemental]
    [time.strptime("11:00", "%H:%M"), Golem Mark II]
    [time.strptime("11:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("11:30", "%H:%M"), Claw of Jormag]
    [time.strptime("11:30", "%H:%M"), Tequatl the Sunless]
    [time.strptime("11:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("12:00", "%H:%M"), Admiral Taidha Covington]
    [time.strptime("12:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("12:30", "%H:%M"), Megadestroyer]
    [time.strptime("12:30", "%H:%M"), Evolved Jungle Wurm]
    [time.strptime("12:45", "%H:%M"), Fire Elemental]
    [time.strptime("13:00", "%H:%M"), The Shatterer]
    [time.strptime("13:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("13:30", "%H:%M"), Modniir Ulgoth]
    [time.strptime("13:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("14:00", "%H:%M"), Golem Mark II]
    [time.strptime("14:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("14:30", "%H:%M"), Claw of Jormag]
    [time.strptime("14:45", "%H:%M"), Fire Elemental]
    [time.strptime("15:00", "%H:%M"), Admiral Taidha Covington]
    [time.strptime("15:00", "%H:%M"), Karka Queen]
    [time.strptime("15:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("15:30", "%H:%M"), Megadestroyer]
    [time.strptime("15:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("16:00", "%H:%M"), The Shatterer]
    [time.strptime("16:00", "%H:%M"), Tequatl the Sunless]
    [time.strptime("16:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("16:30", "%H:%M"), Modniir Ulgoth]
    [time.strptime("16:45", "%H:%M"), Fire Elemental]
    [time.strptime("17:00", "%H:%M"), Golem Mark II]
    [time.strptime("17:00", "%H:%M"), Evolved Jungle Wurm]
    [time.strptime("17:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("17:30", "%H:%M"), Claw of Jormag]
    [time.strptime("17:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("18:00", "%H:%M"), Admiral Taidha Covington]
    [time.strptime("18:00", "%H:%M"), Karka Queen]
    [time.strptime("18:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("18:30", "%H:%M"), Megadestroyer]
    [time.strptime("18:45", "%H:%M"), Fire Elemental]
    [time.strptime("19:00", "%H:%M"), The Shatterer]
    [time.strptime("19:00", "%H:%M"), Tequatl the Sunless]
    [time.strptime("19:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("19:30", "%H:%M"), Modniir Ulgoth]
    [time.strptime("19:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("20:00", "%H:%M"), Golem Mark II]
    [time.strptime("20:00", "%H:%M"), Evolved Jungle Wurm]
    [time.strptime("20:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("20:30", "%H:%M"), Claw of Jormag]
    [time.strptime("20:45", "%H:%M"), Fire Elemental]
    [time.strptime("21:00", "%H:%M"), Admiral Taidha Covington]
    [time.strptime("21:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("21:30", "%H:%M"), Megadestroyer]
    [time.strptime("21:45", "%H:%M"), Shadow Behemoth]
    [time.strptime("22:00", "%H:%M"), The Shatterer]
    [time.strptime("22:15", "%H:%M"), Svanir Shaman Chief]
    [time.strptime("22:30", "%H:%M"), Modniir Ulgoth]
    [time.strptime("22:45", "%H:%M"), Fire Elemental]
    [time.strptime("23:00", "%H:%M"), Golem Mark II]
    [time.strptime("23:00", "%H:%M"), Karka Queen]
    [time.strptime("23:15", "%H:%M"), Great Jungle Wurm]
    [time.strptime("23:30", "%H:%M"), Claw of Jormag]
    [time.strptime("23:45", "%H:%M"), Shadow Behemoth]
]