--- 
!Event
  name: "Admiral Taidha Covington"
  times: [ "00:00", "03:00", 
           "06:00", "09:00",
           "12:00", "15:00",
           "18:00","21:00" ]

--- 
!Event
  name: "Claw of Jormag"
  times: [ "02:30", "05:30",
           "08:30", "11:30",
           "14:30", "17:30",
           "20:30", "23:30" ]
